<?php 

/**
* Implement hook_form_alter().
*/

function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    if($form_id = 'user-login-form'){
        $form['#title'] = t('Login with your information');
        $form['name']['#attributes']['placeholder']=('Enter your user name');
        $form['pass']['#attributes']['placeholder']=('Enter your password');
    }
}

/**
* Implemet hook_preprocess_page().
*/

function first_module_preprocess_page(&$variable){
    $variable['first_module_variable'] = 'My first Drupal 10';
}
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function first_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.first_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a first custom module.') . '</p>';
      return $output;
  }
}
